### PR TITLE
Feature fkuhbier display animal profile swp23 mtv 75 into development

### PR DESCRIPTION
**Pull request by FelixAlexK**
Added detail dialog for animal profile

### CODE REVIEW

**Review by aln0c — DISMISSED** [review]
no results while there is "suchen" inside the edittext. Try deleting the String inside the Edittext and add a hint(suchen), so it shows all animals

**Review by aln0c — CHANGES_REQUESTED** [review]
Bildschirmfoto 2023-06-23 um 18 57 22
textfield with description would be better, cause i dont know what is "n.a"
example: 
Spezies: Reptilien
Rasse: Echsen
Geschlecht: männlich 
and so on

**Comment by FelixAlexK** [comment]
image
Better now?

**Review by FelixAlexK — COMMENTED** [review]
image
fine?

**Comment by FelixAlexK** [comment]
> 

done

**Review by FelixAlexK — COMMENTED** [review]
^_____^

**Comment by FelixAlexK** [comment]
> Bildschirmfoto 2023-06-23 um 18 57 22 textfield with description would be better, cause i dont know what is "n.a" example: Spezies: Reptilien Rasse: Echsen Geschlecht: männlich and so on

Changed!

**Review by aln0c — APPROVED** [review]
looks better! Very good stuff. I'm really proud of you!

**Pull request merged**
